/*****************************************************************
 *
 * Author: Brandon
 * Date Created: 30 Nov. 2017
 * File : ErrorListDialog.java
 *
 * Copyright (c) 2017 Brandon Quinn
 *
 *****************************************************************/

package elara.editor.ui;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JList;
import elara.editor.debug.Log;
import elara.editor.debug.RenderDebug;

/*****************************************************************
 *
 * ErrorListDialog
 *
 * Description: A dialog used to display a list of Log instances
 * generated by the RenderDebug class.
 *
 *****************************************************************/

public class ErrorListDialog
	extends JDialog
{
	private static final long serialVersionUID = 1L;
	
	private static ErrorListDialog dialog = new ErrorListDialog();
	private static JList<Log> errorList = new JList<Log>();
	private static DefaultListModel<Log> model = new DefaultListModel<Log>();
	
	private static int previousSize = -1;
	
	public static void display()
	{
		
		dialog.setTitle("Errors and Warnings");
		dialog.setLayout(new BorderLayout());
		dialog.setSize(500, 500);
		dialog.setLocationRelativeTo(null);
		dialog.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
		errorList.setCellRenderer(new ErrorListRenderer());
		dialog.add(errorList, BorderLayout.CENTER);
		ArrayList<Log> logs = RenderDebug.logs();
		for (Log log : logs) model.addElement(log);
		errorList.setModel(model);
		dialog.setVisible(true);
	}

	/**
	 * Put this in the render loop to make sure the 
	 */
	public static void update()
	{
		if (RenderDebug.logs().size() == -1 || RenderDebug.logs().size() != previousSize) {
			model.clear();
			ArrayList<Log> logs = RenderDebug.logs();
			for (Log log : logs) model.addElement(log);
			previousSize = logs.size();
		}
	}
}
